version: '3'
services:
  web:
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=test.local
    links:
      - php
    restart: always
  php:
    image: thecodingmachine/php:8.1-v4-fpm
    volumes:
      - ./src:/var/www
    restart: always



