version: '3'
services:
  web:
    image: nginx:alpine
    working_dir: /var/www
    ports:
      - "80:80"
    volumes:
      - './docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www:cached'
    environment:
      - NGINX_HOST=test.local
    links:
      - php
    restart: always
  php:
    image: 'devilbox/php-fpm:8.0-work'
    restart: always
    working_dir: /var/www
    volumes:
      - './docker/etc/php/php.ini:/usr/local/etc/php/php.ini'
      - './docker/etc/php/xxx-devilbox-default-php.ini:/usr/local/etc/php/conf.d/xxx-devilbox-default-php.ini'
      - './:/var/www:cached'



